import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Header.module.css'
import { useEffect, useReducer, useState } from 'react'

export default function Header() {

    function renderHeader(){
        return(
            <div>
                <div className={styles.logo_container}>
                    <div>
                        <Image className={styles.large_icon} width={65} height={65} src={require('../public/icons/logo_large.png')} />
                        <Image className={styles.small_icon} width={50} height={50} src={require('../public/icons/logo_large.png')} />
                    </div>
                    <div>
                        Password Manager
                    </div>
                </div>
            </div>
        )
    }

    return (
        <>
            <Head>
                <title>Password Manager</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {renderHeader()}
        </>
    )
}
