import React, {useState, useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import {API} from '../API'

import styles from '../styles/Banking.module.css'

export default function Banking() {

    const[passwords, setPasswords] = useState(null);

    const fetchPasswords = () => {
        fetch(`${API}/passwords/getBankingPasswords`)
        .then(res=>res.json())
        .then(result=>{
            setPasswords(result)
        })
        .catch((e) => {
            setPasswords("network_error")
        })
    }

    useEffect(() => {
        fetchPasswords()
    }, []);

    function renderHeader(){
        return(
            <div className={styles.header_container}>
                Banking
            </div>
        )
    }

    function renderCategories(){
        return(
            <div className={styles.category_container}>
                <div className={styles.category}>All</div>
                <div className={styles.category}>Archive</div>
            </div>
        )
    }

    function renderPasswords(){
        return(
            <div className={styles.password_container}>
                {passwords.map(item=>{
                    return(
                        <div key={item._id} className={` ${styles.password_card} ${styles.mItem}}`}>
                            <div className={styles.password_logo}> 
                                {item.name.substring(0,1).toUpperCase()}
                            </div>
                            <div className={styles.password_detail}>
                                <div>{item.name}</div>
                                <div>{item.email}</div>
                            </div>
                            <div className={styles.password_arrow}> 
                                <Image alt='right_arrow' src={require('../public/icons/right_arrow.svg')} />
                            </div>
                        </div>
                    )
                })}
            </div>
        )
    }

    function renderLoading(){
        return(
            <div>
                Loading...
            </div>
        )
    }

    return (
        <>
            <Head>
                <title>Passwords</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.password_page}>
                <div className={styles.container}>
                    {renderHeader()}
                    {renderCategories()}
                    {passwords==null ? renderLoading() : renderPasswords()}
                </div>
            </div>
        </>
    )
}
