import Head from 'next/head'
import Image from 'next/image'
import Home from './Home'
import { useEffect, useState } from 'react'
import styles from '../styles/Index.module.css'
import { API } from '../API'

export default function Index() {
    
    const[auth, setAuth] = useState(null)
    const[verified, setVerified] = useState(null)
    const[macAddress, setMacAddress] = useState(null)
    const validMacAddresses = []

    const fetchAuth = () => {
        fetch(`${API}/getMacAddress`)
        .then(res=>res.json())
        .then(result=>{
            setMacAddress(result)
            validMacAddresses.includes(result) ? setVerified(true) : setVerified(false)
        })
        .catch((e) => {
            console.log("Error in Fetching /getMacAddress "+e);
        })
    }

    useEffect(()=>{
        fetchAuth()
    },[])

    function verifyAuth(){
        auth.substring(0,5)=="14352" && auth.substring(5)=="74849" ? setVerified(true) : null
    }

    function renderAuth(){
        return(
            <div className={styles.auth_container}>
                {macAddress==null ? loading() : !verified ?
                <div>
                    <Image width={100} height={100} src={require('../public/icons/logo_large.png')} />
                    <div className={styles.warning}>
                        Your mac address <span>{macAddress}</span> does not match to owner&apos;s mac adddress.
                    </div>
                    <div className={styles.input_container}>
                        <input type="password" placeholder="password" value={auth} onChange={e => setAuth(e.target.value)} />
                        <button onClick={() => verifyAuth()}><Image width={30} src={require('../public/icons/right_arrow.png')} /></button>
                    </div>
                </div>
                :null}
            </div>
        )
    }

    function loading(){
        return(
            <div className={styles.loading_container}>
                <div className={styles.loader} />
                <Image width={100} height={100} src={require('../public/icons/logo_large.png')} />
            </div>
        )
    }

    return (
        <>
            <Head>
                <title>Password Manager</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            {verified ? <Home /> : renderAuth()}
        </>
    )
}
