import Head from 'next/head'
import Image from 'next/image'
import Home from './Home'
import { useEffect, useState } from 'react'
import styles from '../styles/Index.module.css'

export default function Index() {
    
    const password = "1435274849";
    const[auth, setAuth] = useState(null)
    const[verified, setVerified] = useState(false)

    function verifyAuth(){
        auth==password ? setVerified(true) : null
    }

    function renderAuth(){
        return(
            <div className={styles.auth_container}>
                <Image width={100} height={100} src={require('../public/icons/logo_large.png')} />
                <input value={auth} onChange={e => setAuth(e.target.value)} />
                <button onClick={() => verifyAuth()}>enter</button>
            </div>
        )
    }

    return (
        <>
            <Head>
                <title>Password Manager</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            {verified ? <Home /> : renderAuth()}
        </>
    )
}
