import React, {useState, useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import {API} from '../API'

import Passwords from '@/components/Passwords'

export default function Home() {

    const[navigation, setNavigation] = useState("Passwords")

    const[enableAuth, setEnableAuth] = useState(false)
    const[loading, setLoading] = useState(false)
    const[password, setPassword] = useState("")

    const fetchAuth = () =>{
        setLoading(true)
        fetch(`${API}/getAuthentication`,{
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ 
                "password" : password
            })
    
        })
        .then(res=>res.json())
        .then(result=>{
            result?setEnableAuth(true):setPassword("")
            setLoading(false)
        })
        .catch((e) => {
            console.log("Error in Password Auth Occurred " + e)
            setLoading(false)
        })
    }

    function renderAuthContainer(){
        return(
            <div>
                <input value={password} onChange={e => setPassword(e.target.value)} placeholder='password' />
                <button onClick={() => fetchAuth()}>Click</button>
            </div>
        )
    }

    function renderPasswordApp(){
        return(
            <div>
                {navigation=="Passwords" && <Passwords />}
                {/* {renderNavbar()} */}
            </div>
        )
    }

    function renderNavbar(){
        return(
            <div>
                <button onClick={() => setNavigation("Passwords")}>Passwords</button>
                <button onClick={() => setNavigation("Banking")}>Banking</button>
                <button onClick={() => setNavigation("Manage")}>Manage</button>
            </div>
        )
    }

    function renderLoading(){
        return(
            <div>
                Loading...
            </div>
        )
    }

    return (
        <>
            <Head>
                <title>Passwords</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {loading ? renderLoading() : enableAuth ? renderPasswordApp() : renderAuthContainer()}
        </>
    )
}
