import React, {useState, useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Index.module.css'
import {API} from '../API'

import Passwords from '@/components/Passwords'
import Banking from '@/components/Banking'
import Manage from '@/components/Manage'

export default function Home() {

    const[currentPage, setCurrentPage] = useState("Passwords")

    const[enableAuth, setEnableAuth] = useState(false)
    const[loading, setLoading] = useState(false)
    const[password, setPassword] = useState("")

    const fetchAuth = () =>{
        setLoading(true)
        fetch(`${API}/getAuthentication`,{
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ 
                "password" : password
            })
    
        })
        .then(res=>res.json())
        .then(result=>{
            result?setEnableAuth(true):setPassword("")
            setLoading(false)
        })
        .catch((e) => {
            console.log("Error in Password Auth Occurred " + e)
            setLoading(false)
        })
    }

    function renderAuthContainer(){
        return(
            <div className={styles.auth_page}>
                Enter your password
                <div className={styles.auth_container}>
                    <input value={password} onChange={e => setPassword(e.target.value)} placeholder='password' />
                    <button onClick={() => fetchAuth()}>Click</button>
                </div>
            </div>
        )
    }

    function renderPasswordApp(){
        return(
            <div>
                {currentPage=="Passwords" && <Passwords />}
                {currentPage=="Banking" && <Banking />}
                {currentPage=="Manage" && <Manage />}
                {renderNavbar()}
            </div>
        )
    }

    function renderNavbar(){
        return(
            <div className={styles.container}>
                <div className={`${styles.navbar}`}>
                    <a onClick={()=>setCurrentPage("Passwords")}>Passwords</a>
                    <a onClick={()=>setCurrentPage("Banking")}>Banking</a>
                    <a onClick={()=>setCurrentPage("Manage")}>Manage</a>
                </div>
            </div>
        )
    }

    function renderLoading(){
        return(
            <div>
                Loading...
            </div>
        )
    }

    return (
        <>
            <Head>
                <title>Passwords</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {loading ? renderLoading() : enableAuth ? renderPasswordApp() : renderAuthContainer()}
        </>
    )
}
