import Head from 'next/head'
import Home from '@/components/Home'
import Passwords from '@/components/Passwords'
import Banking from '@/components/Banking'

export default function Index() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head> 
            <div>
                {/* <Home /> */}
                <Passwords />
                {/* <Banking /> */}
            </div>
        </>
    )
}
